import { PublicFrame } from "@/components/PublicFrame";

export const metadata = { title: "Imaje · Mission", description: "Teach young people to make films with AI: creatively, with integrity, and honest about the footprint." };

export default function Mission() {
  return (
    <PublicFrame current="mission">
      <p className="label mb-3">Mission</p>
      <h1 className="display mb-6 text-4xl leading-tight" style={{ textWrap: "balance" }}>Teach young people to make films with AI, and to make them well.</h1>
      <p className="mb-10 max-w-[62ch] text-lg leading-relaxed">
        The tools are here. Fourteen-year-olds can already generate a shot in a minute. What they can&apos;t get anywhere is a place that teaches
        the craft around the button: what a cut is for, whose face is in it, what it cost, and what to do when the machine gives you
        something you didn&apos;t ask for. Imaje is that place. A studio built for cohorts, where the film comes first and the model is a crew member.
      </p>

      <h2 className="display mb-3 text-2xl">Three promises</h2>
      <div className="mb-10 grid gap-4 sm:grid-cols-3">
        <section className="card p-5">
          <div className="label mb-2 text-dim">Creative</div>
          <p className="text-sm leading-relaxed">Students write the brief, draw the board, choose the look, and direct the take. Explore cheaply, compare honestly, finish deliberately. The messy first takes are the lesson, not a mistake.</p>
        </section>
        <section className="card p-5">
          <div className="label mb-2 text-ok">Integrity</div>
          <p className="text-sm leading-relaxed">Every model is rated on what it was trained on, what its licence allows, where it runs, and what it discloses. Every real person has a signed release before they appear. Every take has a receipt.</p>
        </section>
        <section className="card p-5">
          <div className="label mb-2 text-dim">Footprint, honestly</div>
          <p className="text-sm leading-relaxed">We don&apos;t call Imaje carbon neutral, because we can&apos;t measure it yet. We rate what each model discloses, never invent a number, and are building towards measuring every take on our own machines, then funding carbon removal beyond it.</p>
        </section>
      </div>

      <h2 className="display mb-3 text-2xl">What integrity means here</h2>
      <ul className="mb-10 max-w-[62ch] space-y-3 text-[15px] leading-relaxed">
        <li><b>Consent is specific.</b> A character built on a real person needs a release that names the person, the uses, and the lane it permits. Revoke it, and generation stops. Nothing about an under-18 is ever cloned: voice, face, or likeness.</li>
        <li><b>Thirteen and up.</b> Imaje isn&apos;t for children under 13. Whoever invites a student confirms they&apos;re 13 or older, and the student confirms it again when they join. Under-18s are protected as minors throughout.</li>
        <li><b>Other people&apos;s work stays theirs.</b> Prompts are also checked for well-known characters, brands, famous people and living artists&apos; styles. Students get a reason and a way to make the idea their own.</li>
        <li><b>Prompts pass a gate.</b> Before a prompt reaches a model, it&apos;s checked against the school&apos;s content tier. A refusal costs nothing and comes with one sentence a teacher can show the student.</li>
        <li><b>Models are rows in a register, not a brand.</b> Training-data disclosure, licence, indemnity, likeness risk, hosting region, energy disclosure. Students see the rating on the tile before they spend a token.</li>
        <li><b>Stock voices, plainly.</b> The ready-made voices come from an open model trained on public-domain and openly licensed recordings, plus some speech generated by commercial voice models whose sources aren&apos;t public. That second part isn&apos;t licensed, and we&apos;re working on replacing it: next is a set of voices performed by paid actors who agreed to this use, on a model trained only on public-domain speech and their recordings.</li>
        <li><b>Receipts are permanent.</b> Which model, which version, which prompt, whose consent, what it cost, what it likely used. Kill a take and it leaves the bin, never the record.</li>
      </ul>

      <h2 className="display mb-3 text-2xl">Our footprint, honestly</h2>
      <p className="mb-4 max-w-[62ch] text-[15px] leading-relaxed">
        Imaje isn&apos;t carbon neutral, and we won&apos;t say it is until we can show the numbers. Today every picture and clip is made
        on a rented service that publishes no energy figures, and almost no video model publishes what a generation costs in energy or water.
        Making a number up would be a lie, so we don&apos;t. Each model carries a disclosure tier: <b>A</b> when the method is published,
        <b>B</b> when only independent research exists, <b>C</b> when there&apos;s nothing. Today nobody is A.
      </p>
      <p className="mb-4 max-w-[62ch] text-[15px] leading-relaxed">
        What independent research does show: a short clip from the family of video models we use measured a few watt-hours on one
        modern GPU, and the energy grows roughly with the <i>square</i> of a clip&apos;s length. Doubling a take&apos;s length roughly quadruples its energy.
        So we teach it on day one: plan the cut, then generate.
      </p>
      <h3 className="mb-2 text-lg font-medium">The path we&apos;re on</h3>
      <ol className="mb-10 max-w-[62ch] list-decimal space-y-2 pl-5 text-[15px] leading-relaxed">
        <li><b>Estimate, labelled as an estimate.</b> A range of energy, carbon and water for each take, from published measurements, with the method on a public page.</li>
        <li><b>Use less.</b> Quick drafts in class by default, short takes, and a final render only for the takes a student keeps.</li>
        <li><b>Measure.</b> Once rendering runs on our own machines, read the actual energy of every take and show it on the receipt, discarded takes included.</li>
        <li><b>Cleaner power.</b> Run those machines where the grid is cleanest, keeping student data in the US.</li>
        <li><b>Go beyond it.</b> Fund durable carbon removal for more than we measure, reported in tonnes contracted and delivered, and called a contribution, not neutrality.</li>
      </ol>

      <h2 className="display mb-3 text-2xl">Why open models</h2>
      <p className="mb-4 max-w-[62ch] text-[15px] leading-relaxed">
        The everyday routes are open-weight. That matters for a school in three plain ways. A student&apos;s film and the faces in it can stay on
        infrastructure the school chooses, rather than becoming someone&apos;s training data. The model can be inspected and, on our own machines, metered,
        which is the only honest route to a real energy number. And the same family carries a cut from first sketch to final take, with camera
        logic, keyframes, extension and synced sound, so the look holds instead of changing every time a student changes tools.
      </p>
      <p className="max-w-[62ch] text-[15px] leading-relaxed">
        Closed models stay on the menu for a finish that wants them, with their ratings shown, never as the default. Openness here is not a slogan;
        it&apos;s what lets us keep the promises above.
      </p>
    </PublicFrame>
  );
}
