-- GENERATED by scripts/build-models-seed.mjs from models.csv, model_versions.csv, deployment_profiles.csv,
-- schemas/*.json and profiles/*.json. Do not edit. Re-running is safe unless a job already references a
-- version/profile whose non-operational fields changed (eduai.registry_guard) — that needs a new slug.
insert into public.models (slug, display_name, modality, creative_guidance)
values
  ('kling', 'Kling', 'image_to_video', 'Final-quality motion from a still. Use when the frame is already right and you need dependable movement.'),
  ('ltx', 'LTX', 'text_to_video', 'Fast video experiments with camera and reference control. Open weights; the Control lane''s home.'),
  ('veo', 'Veo', 'text_to_video', 'Release-quality text-to-video with optional audio. Expensive; save for the finish.'),
  ('flux', 'FLUX', 'text_to_image', 'Stills: storyboards'),
  ('chatterbox', 'Chatterbox', 'text_to_speech', 'Scratch dialogue and permitted voice work. Voice cloning is locked behind consent.'),
  ('stable-audio', 'Stable Audio', 'sound_effects', 'Foley')
on conflict (slug) do update set
  display_name = excluded.display_name,
  modality = excluded.modality,
  creative_guidance = excluded.creative_guidance;

insert into public.model_versions (slug, model_id, version, weights_status, license_family, license_version, license_url, commercial_eligibility, training_data_disclosure, output_rights_summary, self_hostable, voice_likeness_risk, release_eligible, integrity_rating, indemnification, min_content_tier, limitations, safety_pipeline_version, approval_status, approval_owner, approved_at, approved_until, notes, input_schema, safety)
values
  ('veo-3.1-lite', (select id from public.models where slug = 'veo'), '3.1-lite', 'closed', 'Google Cloud Generative AI terms', '2026-05', 'https://cloud.google.com/terms/generative-ai', 'allowed', 'opt_out', 'Outputs owned by the customer; Google indemnifies eligible uses.', false, 'low', true, 'high', true, 'M', 'No character consistency across shots; 8s max.', 'pg-1', 'approved', 'programme-lead', '2026-09-09', '2026-12-31', 'Phase 1 Finish route. UNVERIFIED terms link — confirm before cohort start.', $json${"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string","maxLength":2000,"x-ui":{"widget":"textarea"}},"duration_s":{"type":"integer","enum":[4,6,8],"default":6},"aspect_ratio":{"type":"string","enum":["16:9","9:16"],"default":"16:9"},"resolution":{"type":"string","enum":["720p","1080p"],"default":"720p"},"generate_audio":{"type":"boolean","default":false}}}$json$::jsonb, $json${"output_moderation":true,"prompt_gate":"required"}$json$::jsonb),
  ('ltx-2.5', (select id from public.models where slug = 'ltx'), '2.5', 'open_weight', 'LTX-2.5 Open Weights License', '2.5', 'https://huggingface.co/Lightricks/LTX-2.5', 'threshold', 'undisclosed', 'Outputs usable; commercial use above the revenue threshold requires a licence from Lightricks.', true, 'low', true, 'medium', false, 'M', 'Struggles with hands and text; 8s max at draft quality.', 'pg-1', 'approved', 'programme-lead', '2026-09-09', '2026-12-31', 'Phase 1 Explore/Control route (managed API for now; self-hosted profile is Phase 4).', $json${"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string","maxLength":2000,"x-ui":{"widget":"textarea"}},"image":{"type":"string","format":"asset-ref","title":"Reference frame (optional)","x-ui":{"accept":"image"}},"duration_s":{"type":"integer","enum":[5,8],"default":5},"aspect_ratio":{"type":"string","enum":["16:9","9:16","1:1"],"default":"16:9"},"camera_motion":{"type":"string","x-ui":{"widget":"camera-motion"}},"seed":{"type":"integer","minimum":0}}}$json$::jsonb, $json${"output_moderation":false,"prompt_gate":"required"}$json$::jsonb),
  ('stable-audio-3', (select id from public.models where slug = 'stable-audio'), '3', 'open_weight', 'Stability AI Community License', '2026', 'https://stability.ai/license', 'threshold', 'licensed', 'Outputs usable; enterprise licence above USD 1M revenue.', true, 'none', true, 'high', false, 'M', 'Up to 30s; no dialogue.', 'pg-1', 'approved', 'programme-lead', '2026-09-09', '2026-12-31', 'Phase 1 SFX route.', $json${"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string","maxLength":500},"duration_s":{"type":"number","minimum":1,"maximum":30,"default":5},"seed":{"type":"integer","minimum":0}}}$json$::jsonb, $json${"output_moderation":false,"prompt_gate":"optional"}$json$::jsonb),
  ('kling-3', (select id from public.models where slug = 'kling'), '3', 'closed', 'Kling API terms', '2026', 'https://klingai.com/', 'allowed', 'undisclosed', 'Per vendor terms; review before release.', false, 'low', false, 'medium', false, 'M', 'Chinese-hosted; data residency review pending.', 'pg-1', 'draft', null, null, null, 'Not selectable until rights + residency reviewed.', $json${"type":"object","required":["image","prompt"],"properties":{"image":{"type":"string","format":"asset-ref","title":"Start frame","x-ui":{"accept":"image"}},"prompt":{"type":"string","maxLength":2000,"x-ui":{"widget":"textarea"}},"negative_prompt":{"type":"string","maxLength":500},"duration_s":{"type":"integer","enum":[5,10],"default":5},"camera_motion":{"type":"string","x-ui":{"widget":"camera-motion"}}}}$json$::jsonb, $json${"output_moderation":true,"prompt_gate":"required"}$json$::jsonb),
  ('flux-2-dev', (select id from public.models where slug = 'flux'), '2-dev', 'open_weight', 'FLUX.2 [dev] Non-Commercial License', '2.0', 'https://huggingface.co/black-forest-labs/FLUX.2-dev/blob/main/LICENSE.md', 'non_commercial', 'undisclosed', 'Non-commercial only; outputs may not be released commercially.', true, 'high', false, 'medium', false, 'M', 'Non-commercial licence blocks Release. A pro/licensed version would be a separate row.', 'pg-1', 'draft', null, null, null, 'Not selectable: licence blocks release. Consider FLUX.2 pro via API as a separate version.', $json${"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string","maxLength":2000,"x-ui":{"widget":"textarea"}},"aspect_ratio":{"type":"string","enum":["16:9","9:16","1:1","4:3","3:4"],"default":"16:9"},"num_images":{"type":"integer","minimum":1,"maximum":4,"default":1},"seed":{"type":"integer","minimum":0}}}$json$::jsonb, $json${"output_moderation":true,"prompt_gate":"required"}$json$::jsonb),
  ('chatterbox-1', (select id from public.models where slug = 'chatterbox'), '1', 'open_source', 'MIT', '1.0', 'https://resemble.ai/learn/models/chatterbox', 'allowed', 'undisclosed', 'Outputs usable; voice cloning subject to consent of the voice owner.', true, 'high', true, 'medium', false, 'M', 'Voice cloning from short samples — high likeness risk.', 'pg-1', 'draft', null, null, null, 'Phase 2 voice route; needs the voice_likeness lane + consent workflow first.', $json${"type":"object","required":["text"],"properties":{"text":{"type":"string","maxLength":3000,"x-ui":{"widget":"textarea"}},"voice_reference":{"type":"string","format":"asset-ref","title":"Voice reference (consented)","x-ui":{"accept":"audio","requires_consent":true}},"exaggeration":{"type":"number","minimum":0,"maximum":1,"default":0.5}}}$json$::jsonb, $json${"output_moderation":false,"prompt_gate":"required"}$json$::jsonb)
on conflict (slug) do update set
  model_id = excluded.model_id,
  version = excluded.version,
  weights_status = excluded.weights_status,
  license_family = excluded.license_family,
  license_version = excluded.license_version,
  license_url = excluded.license_url,
  commercial_eligibility = excluded.commercial_eligibility,
  training_data_disclosure = excluded.training_data_disclosure,
  output_rights_summary = excluded.output_rights_summary,
  self_hostable = excluded.self_hostable,
  voice_likeness_risk = excluded.voice_likeness_risk,
  release_eligible = excluded.release_eligible,
  integrity_rating = excluded.integrity_rating,
  indemnification = excluded.indemnification,
  min_content_tier = excluded.min_content_tier,
  limitations = excluded.limitations,
  safety_pipeline_version = excluded.safety_pipeline_version,
  approval_status = excluded.approval_status,
  approval_owner = excluded.approval_owner,
  approved_at = excluded.approved_at,
  approved_until = excluded.approved_until,
  notes = excluded.notes,
  input_schema = excluded.input_schema,
  safety = excluded.safety;

insert into public.deployment_profiles (slug, model_version_id, kind, provider, endpoint, region, credential_policy, lanes, health_status, adapter_tested_at, approval_status, approval_owner, approved_at, approved_until, enabled, notes, cost_model, retention, quota, safety_pipeline_version)
values
  ('veo-3.1-lite@fal', (select id from public.model_versions where slug = 'veo-3.1-lite'), 'managed_api', 'fal', 'fal-ai/veo3.1/lite/text-to-video', 'us', 'either', array['finish'::public.lane], 'untested', '2026-09-09', 'approved', 'programme-lead', '2026-09-09', '2026-12-31', true, 'UNVERIFIED endpoint + cost — confirm against fal docs before P1-10. adapter_tested_at is a placeholder until P1-10 lands.', $json${"kind":"per_second","cents_per_second":15,"duration_field":"duration_s","verified":false}$json$::jsonb, $json${"vendor_retains_inputs":true,"vendor_retention_days":null,"platform_input_days":90,"platform_output_days":365}$json$::jsonb, $json${}$json$::jsonb, (select safety_pipeline_version from public.model_versions where slug = 'veo-3.1-lite')),
  ('ltx-2.5@fal', (select id from public.model_versions where slug = 'ltx-2.5'), 'managed_api', 'fal', 'fal-ai/ltx-2.5/text-to-video', 'us', 'either', array['explore'::public.lane, 'control'::public.lane], 'untested', '2026-09-09', 'approved', 'programme-lead', '2026-09-09', '2026-12-31', true, 'UNVERIFIED endpoint + cost. Managed route; self-hosted profile ltx-2.5@school is Phase 4.', $json${"kind":"per_second","cents_per_second":4,"duration_field":"duration_s","verified":false}$json$::jsonb, $json${"vendor_retains_inputs":false,"vendor_retention_days":0,"platform_input_days":90,"platform_output_days":365}$json$::jsonb, $json${}$json$::jsonb, (select safety_pipeline_version from public.model_versions where slug = 'ltx-2.5')),
  ('stable-audio-3@fal', (select id from public.model_versions where slug = 'stable-audio-3'), 'managed_api', 'fal', 'fal-ai/stable-audio-3/sfx', 'us', 'either', array['explore'::public.lane], 'untested', '2026-09-09', 'approved', 'programme-lead', '2026-09-09', '2026-12-31', true, 'UNVERIFIED endpoint + cost.', $json${"kind":"per_call","cents":5,"verified":false}$json$::jsonb, $json${"vendor_retains_inputs":false,"vendor_retention_days":0,"platform_input_days":90,"platform_output_days":365}$json$::jsonb, $json${}$json$::jsonb, (select safety_pipeline_version from public.model_versions where slug = 'stable-audio-3')),
  ('kling-3@fal', (select id from public.model_versions where slug = 'kling-3'), 'managed_api', 'fal', 'fal-ai/kling-video/v3/standard/image-to-video', 'cn', 'platform', array['finish'::public.lane], 'untested', null, 'draft', null, null, null, false, 'Draft: not selectable.', $json${"kind":"per_second","cents_per_second":28,"duration_field":"duration_s","verified":false}$json$::jsonb, $json${"vendor_retains_inputs":true,"vendor_retention_days":null,"platform_input_days":90,"platform_output_days":365}$json$::jsonb, $json${}$json$::jsonb, (select safety_pipeline_version from public.model_versions where slug = 'kling-3')),
  ('flux-2-dev@fal', (select id from public.model_versions where slug = 'flux-2-dev'), 'managed_api', 'fal', 'fal-ai/flux-2/dev', 'us', 'platform', array['explore'::public.lane], 'untested', null, 'draft', null, null, null, false, 'Draft: licence non-commercial.', $json${"kind":"per_call","cents":3,"multiplier_field":"num_images","verified":false}$json$::jsonb, $json${"vendor_retains_inputs":false,"vendor_retention_days":0,"platform_input_days":90,"platform_output_days":365}$json$::jsonb, $json${}$json$::jsonb, (select safety_pipeline_version from public.model_versions where slug = 'flux-2-dev')),
  ('chatterbox-1@replicate', (select id from public.model_versions where slug = 'chatterbox-1'), 'managed_api', 'replicate', 'resemble-ai/chatterbox', 'us', 'platform', array['voice_likeness'::public.lane], 'untested', null, 'draft', null, null, null, false, 'Draft: Phase 2.', $json${"kind":"per_1k_chars","cents":2,"text_field":"text","verified":false}$json$::jsonb, $json${"vendor_retains_inputs":false,"vendor_retention_days":1,"platform_input_days":30,"platform_output_days":365}$json$::jsonb, $json${}$json$::jsonb, (select safety_pipeline_version from public.model_versions where slug = 'chatterbox-1'))
on conflict (slug) do update set
  model_version_id = excluded.model_version_id,
  kind = excluded.kind,
  provider = excluded.provider,
  endpoint = excluded.endpoint,
  region = excluded.region,
  credential_policy = excluded.credential_policy,
  lanes = excluded.lanes,
  health_status = excluded.health_status,
  adapter_tested_at = excluded.adapter_tested_at,
  approval_status = excluded.approval_status,
  approval_owner = excluded.approval_owner,
  approved_at = excluded.approved_at,
  approved_until = excluded.approved_until,
  enabled = excluded.enabled,
  notes = excluded.notes,
  cost_model = excluded.cost_model,
  retention = excluded.retention,
  quota = excluded.quota,
  safety_pipeline_version = excluded.safety_pipeline_version;
