#!/usr/bin/env bash
# Concatenate packages/db/policies/*.sql → packages/db/migrations/0101_rls_policies.sql.
# --check: exit 1 if the migration is stale (CI).
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
SRC="$ROOT/packages/db/policies"
OUT="$ROOT/packages/db/migrations/0101_rls_policies.sql"

gen() {
  echo "-- 0101: RLS policies. GENERATED by scripts/build-policies.sh from packages/db/policies/*.sql."
  echo "-- Do not edit: change the per-table file and run \`pnpm policies:build\`."
  for f in $(ls "$SRC"/*.sql | sort); do
    echo
    echo "-- ---- $(basename "$f" .sql) ----"
    cat "$f"
  done
}

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -u "$OUT" <(gen) >/dev/null; then
    echo "0101_rls_policies.sql is stale. Run: pnpm policies:build" >&2
    diff -u "$OUT" <(gen) >&2 || true
    exit 1
  fi
  echo "policies: in sync"
else
  gen > "$OUT"
  echo "wrote $OUT"
fi
