-- 0101: RLS policies. GENERATED by scripts/build-policies.sh from packages/db/policies/*.sql.
-- Do not edit: change the per-table file and run `pnpm policies:build`.

-- ---- assets ----
create policy assets_select on public.assets for select to authenticated
  using (case when project_id is null then eduai.is_org_admin(org_id) else eduai.can_access_project(project_id) end);
-- users upload; generated/rendered assets come from the orchestrator (service role)
create policy assets_insert on public.assets for insert to authenticated
  with check (project_id is not null and eduai.can_access_project(project_id)
              and source = 'uploaded' and created_by = auth.uid());
-- immutable: no update/delete

-- ---- assistant_events ----
create policy assistant_events_select on public.assistant_events for select to authenticated
  using (user_id = auth.uid() or (cohort_id is not null and eduai.can_manage_cohort(cohort_id)));
-- written by the orchestrator's /assist/* under service role

-- ---- bible_entries ----
create policy bible_entries_select on public.bible_entries for select to authenticated
  using (eduai.can_access_project(project_id));
create policy bible_entries_insert on public.bible_entries for insert to authenticated
  with check (eduai.can_access_project(project_id) and created_by = auth.uid());
create policy bible_entries_update on public.bible_entries for update to authenticated
  using (eduai.can_access_project(project_id)) with check (eduai.can_access_project(project_id));
create policy bible_entries_delete on public.bible_entries for delete to authenticated
  using (eduai.can_access_project(project_id));

-- ---- cohort_instructors ----
create policy cohort_instructors_select on public.cohort_instructors for select to authenticated
  using (eduai.can_view_cohort(cohort_id));
create policy cohort_instructors_write on public.cohort_instructors for all to authenticated
  using (eduai.is_org_admin(org_id)) with check (eduai.is_org_admin(org_id));

-- ---- cohort_modules ----
create policy cohort_modules_select on public.cohort_modules for select to authenticated
  using (eduai.can_view_cohort(cohort_id));
create policy cohort_modules_insert on public.cohort_modules for insert to authenticated
  with check (eduai.is_org_admin(org_id));
-- instructors adjust dates and unlock gates for their cohorts
create policy cohort_modules_update on public.cohort_modules for update to authenticated
  using (eduai.can_manage_cohort(cohort_id)) with check (eduai.can_manage_cohort(cohort_id));
create policy cohort_modules_delete on public.cohort_modules for delete to authenticated
  using (eduai.is_org_admin(org_id));

-- ---- cohorts ----
create policy cohorts_select on public.cohorts for select to authenticated
  using (eduai.can_view_cohort(id));
create policy cohorts_write on public.cohorts for all to authenticated
  using (eduai.is_org_admin(org_id)) with check (eduai.is_org_admin(org_id));

-- ---- consent_releases ----
create policy consent_releases_select on public.consent_releases for select to authenticated
  using (eduai.can_access_project(project_id));
-- members upload a release (pending or signed); only instructors/admins change state afterwards (revoke)
create policy consent_releases_insert on public.consent_releases for insert to authenticated
  with check (eduai.can_access_project(project_id) and created_by = auth.uid() and state <> 'revoked');
create policy consent_releases_update on public.consent_releases for update to authenticated
  using (eduai.can_manage_project(project_id)) with check (eduai.can_manage_project(project_id));
-- no delete: releases are evidence

-- ---- courses ----
create policy courses_select on public.courses for select to authenticated
  using (eduai.is_org_member(org_id));
create policy courses_write on public.courses for all to authenticated
  using (eduai.is_org_admin(org_id)) with check (eduai.is_org_admin(org_id));

-- ---- deployment_profiles ----
create policy deployment_profiles_select on public.deployment_profiles for select to authenticated using (true);

-- ---- enrolments ----
create policy enrolments_select on public.enrolments for select to authenticated
  using (user_id = auth.uid() or eduai.can_manage_cohort(cohort_id));
create policy enrolments_write on public.enrolments for all to authenticated
  using (eduai.is_org_admin(org_id)) with check (eduai.is_org_admin(org_id));

-- ---- invites ----
create policy invites_select on public.invites for select to authenticated
  using (eduai.is_org_admin(org_id));
create policy invites_insert on public.invites for insert to authenticated
  with check (eduai.can_grant_role(org_id, role) and invited_by = auth.uid());
create policy invites_update on public.invites for update to authenticated
  using (eduai.is_org_admin(org_id) and accepted_at is null)
  with check (eduai.can_grant_role(org_id, role));
create policy invites_delete on public.invites for delete to authenticated
  using (eduai.is_org_admin(org_id) and accepted_at is null);
-- acceptance runs through eduai.accept_invite under service role

-- ---- job_events ----
create policy job_events_select on public.job_events for select to authenticated
  using (exists (select 1 from public.jobs j where j.id = job_id and eduai.can_access_project(j.project_id)));
-- append-only, written by eduai.* functions

-- ---- job_receipts ----
create policy job_receipts_select on public.job_receipts for select to authenticated
  using (exists (select 1 from public.jobs j where j.id = job_id and eduai.can_access_project(j.project_id)));
-- written once by eduai.settle_job

-- ---- jobs ----
create policy jobs_select on public.jobs for select to authenticated
  using (eduai.can_access_project(project_id));
-- org_id / cohort_id / provider are filled by the eduai.jobs_fill_defaults trigger before this check
create policy jobs_insert on public.jobs for insert to authenticated
  with check (eduai.can_access_project(project_id) and requested_by = auth.uid() and status = 'queued');
-- the only user-side transition: cancel while still queued
create policy jobs_cancel on public.jobs for update to authenticated
  using (requested_by = auth.uid() and status = 'queued')
  with check (requested_by = auth.uid() and status = 'cancelled');

-- ---- ledger ----
create policy ledger_select on public.ledger for select to authenticated
  using ((project_id is not null and eduai.can_access_project(project_id))
         or user_id = auth.uid()
         or eduai.can_manage_cohort(cohort_id));
-- append-only, written by eduai.* functions under service role

-- ---- memberships ----
create policy memberships_select on public.memberships for select to authenticated
  using (eduai.is_org_member(org_id));
create policy memberships_insert on public.memberships for insert to authenticated
  with check (eduai.can_grant_role(org_id, role));
create policy memberships_update on public.memberships for update to authenticated
  using (role <> 'owner' and eduai.can_grant_role(org_id, role))
  with check (eduai.can_grant_role(org_id, role));
create policy memberships_delete on public.memberships for delete to authenticated
  using (role <> 'owner' and eduai.can_grant_role(org_id, role));

-- ---- model_versions ----
-- readable including drafts/retired so the UI can explain why a tile is locked
create policy model_versions_select on public.model_versions for select to authenticated using (true);

-- ---- models ----
-- registry is global and readable; every write is service role (seed / admin tooling)
create policy models_select on public.models for select to authenticated using (true);

-- ---- modules ----
create policy modules_select on public.modules for select to authenticated
  using (eduai.is_org_member(org_id));
create policy modules_write on public.modules for all to authenticated
  using (eduai.is_org_admin(org_id)) with check (eduai.is_org_admin(org_id));

-- ---- org_credentials ----
-- secret_ref is a Vault id, not the secret; still admin-only. Revoke = update revoked_at; no delete.
create policy org_credentials_select on public.org_credentials for select to authenticated
  using (eduai.is_org_admin(org_id));
create policy org_credentials_insert on public.org_credentials for insert to authenticated
  with check (eduai.is_org_admin(org_id) and created_by = auth.uid());
create policy org_credentials_update on public.org_credentials for update to authenticated
  using (eduai.is_org_admin(org_id)) with check (eduai.is_org_admin(org_id));

-- ---- org_model_profiles ----
create policy org_model_profiles_select on public.org_model_profiles for select to authenticated
  using (eduai.is_org_member(org_id));
create policy org_model_profiles_write on public.org_model_profiles for all to authenticated
  using (eduai.is_org_admin(org_id)) with check (eduai.is_org_admin(org_id) and approved_by = auth.uid());

-- ---- orgs ----
create policy orgs_select on public.orgs for select to authenticated
  using (eduai.is_org_member(id));
create policy orgs_update on public.orgs for update to authenticated
  using (eduai.is_org_admin(id)) with check (eduai.is_org_admin(id));
-- no insert/delete: orgs are created and deleted by service role (owner-only, out of band)

-- ---- personal_budgets ----
create policy personal_budgets_select on public.personal_budgets for select to authenticated
  using (user_id = auth.uid() or eduai.can_manage_cohort(cohort_id));
create policy personal_budgets_write on public.personal_budgets for all to authenticated
  using (eduai.can_manage_cohort(cohort_id)) with check (eduai.can_manage_cohort(cohort_id));

-- ---- project_budgets ----
create policy project_budgets_select on public.project_budgets for select to authenticated
  using (eduai.can_access_project(project_id));
create policy project_budgets_write on public.project_budgets for all to authenticated
  using (eduai.can_manage_project(project_id)) with check (eduai.can_manage_project(project_id));

-- ---- project_members ----
create policy project_members_select on public.project_members for select to authenticated
  using (eduai.can_access_project(project_id));
create policy project_members_write on public.project_members for all to authenticated
  using (eduai.can_manage_project(project_id)) with check (eduai.can_manage_project(project_id));

-- ---- projects ----
create policy projects_select on public.projects for select to authenticated
  using (eduai.can_access_project(id));
create policy projects_insert on public.projects for insert to authenticated
  with check (eduai.can_manage_cohort(cohort_id));
create policy projects_update on public.projects for update to authenticated
  using (eduai.can_access_project(id)) with check (eduai.can_access_project(id));
create policy projects_delete on public.projects for delete to authenticated
  using (eduai.can_manage_cohort(cohort_id));

-- ---- publications ----
create policy publications_select on public.publications for select to authenticated
  using (eduai.can_access_project(project_id));
-- students never publish; the Release screen is the instructor's
create policy publications_insert on public.publications for insert to authenticated
  with check (eduai.can_manage_project(project_id) and created_by = auth.uid());
create policy publications_update on public.publications for update to authenticated
  using (eduai.can_manage_project(project_id)) with check (eduai.can_manage_project(project_id));

-- ---- scenes ----
create policy scenes_all on public.scenes for all to authenticated
  using (eduai.can_access_project(project_id)) with check (eduai.can_access_project(project_id));

-- ---- shot_bible_entries ----
create policy shot_bible_entries_all on public.shot_bible_entries for all to authenticated
  using (exists (select 1 from public.shots s where s.id = shot_id and eduai.can_access_project(s.project_id)))
  with check (exists (select 1 from public.shots s where s.id = shot_id and eduai.can_access_project(s.project_id)));

-- ---- shots ----
create policy shots_all on public.shots for all to authenticated
  using (eduai.can_access_project(project_id)) with check (eduai.can_access_project(project_id));

-- ---- social_accounts ----
create policy social_accounts_select on public.social_accounts for select to authenticated
  using (eduai.is_org_member(org_id) and (owner_user_id is null or owner_user_id = auth.uid() or eduai.is_org_admin(org_id)));
-- org accounts: admins. personal accounts: the member themself, never a minor (trigger enforces too)
create policy social_accounts_insert on public.social_accounts for insert to authenticated
  with check ((owner_user_id is null and eduai.is_org_admin(org_id))
              or (owner_user_id = auth.uid() and eduai.is_org_member(org_id) and not eduai.is_minor_in(org_id)));
create policy social_accounts_update on public.social_accounts for update to authenticated
  using ((owner_user_id is null and eduai.is_org_admin(org_id)) or owner_user_id = auth.uid())
  with check ((owner_user_id is null and eduai.is_org_admin(org_id)) or owner_user_id = auth.uid());

-- ---- submissions ----
create policy submissions_select on public.submissions for select to authenticated
  using (eduai.can_access_project(project_id));
create policy submissions_insert on public.submissions for insert to authenticated
  with check (eduai.can_access_project(project_id) and submitted_by = auth.uid() and status = 'submitted');
-- review is an instructor/admin act
create policy submissions_update on public.submissions for update to authenticated
  using (eduai.can_manage_project(project_id)) with check (eduai.can_manage_project(project_id));

-- ---- takes ----
create policy takes_select on public.takes for select to authenticated
  using (eduai.can_access_project(project_id));
-- kill / notes only; inserts come from the orchestrator at settle
create policy takes_update on public.takes for update to authenticated
  using (eduai.can_access_project(project_id)) with check (eduai.can_access_project(project_id));

-- ---- timelines ----
create policy timelines_select on public.timelines for select to authenticated
  using (eduai.can_access_project(project_id));
create policy timelines_insert on public.timelines for insert to authenticated
  with check (eduai.can_access_project(project_id) and created_by = auth.uid());
create policy timelines_update on public.timelines for update to authenticated
  using (eduai.can_access_project(project_id)) with check (eduai.can_access_project(project_id));
-- no delete: versions are history

-- ---- users ----
create policy users_select on public.users for select to authenticated
  using (id = auth.uid() or eduai.shares_org_with(id));
create policy users_update on public.users for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());
-- insert happens via the auth.users trigger

-- ---- webhook_inbox ----
-- intentionally no policies: service role only (Cloudflare Worker writes, orchestrator drains)
